import type { IdeaArea, IdeaRow } from "./types";

export const TECH: Partial<Record<IdeaArea, IdeaRow[]>> = {
  tecnologia: [
    ["html", "Aprender HTML desde cero", 1, 20, 4, 3, "Sigue la guía de HTML de MDN Web Docs y maqueta tu propia página personal en un solo archivo.", ["css", "javascript"]],
    ["css", "Aprender CSS moderno (Flexbox y Grid)", 2, 40, 5, 4, "Curso gratuito «Responsive Web Design» de freeCodeCamp y los juegos Flexbox Froggy y Grid Garden. Copia el diseño de 3 webs reales.", ["html", "javascript", "tailwind", "ui-design"]],
    ["javascript", "Aprender JavaScript", 3, 120, 5, 5, "«JavaScript Algorithms and Data Structures» de freeCodeCamp o javascript.info. Programa 5 mini proyectos: reloj, lista de tareas, calculadora, juego y una app con una API.", ["typescript", "react", "nodejs"]],
    ["typescript", "Aprender TypeScript", 3, 40, 5, 5, "Lee el «TypeScript Handbook» oficial y convierte a TypeScript un proyecto tuyo de JavaScript.", ["react", "nodejs"]],
    ["react", "Crear interfaces con React", 3, 80, 5, 5, "Sigue el tutorial de react.dev («Thinking in React») y construye una app de notas con estado, rutas y datos de una API.", ["nextjs", "react-native"]],
    ["nextjs", "Crear webs completas con Next.js", 3, 60, 5, 5, "Curso gratuito «Learn Next.js» de nextjs.org; publica el resultado en Vercel.", ["supabase", "seo"]],
    ["tailwind", "Diseñar rápido con Tailwind CSS", 2, 15, 4, 4, "Documentación oficial de Tailwind; rehaz una página que ya hayas hecho con CSS normal.", ["css"]],
    ["python", "Aprender Python", 2, 100, 5, 5, "«Automate the Boring Stuff with Python» (gratis online) o CS50P de Harvard. Automatiza una tarea real de tu día.", ["data-analysis", "machine-learning", "automation", "django"]],
    ["sql", "Aprender SQL y bases de datos", 2, 40, 5, 5, "SQLBolt y el curso de SQL de Khan Academy; luego diseña la base de datos de una app propia.", ["data-analysis", "supabase", "backend"]],
    ["git", "Dominar Git y GitHub", 2, 15, 5, 4, "Lee «Pro Git» (gratis en git-scm.com) y sube todos tus proyectos a GitHub con commits claros.", ["open-source"]],
    ["linux", "Usar Linux y la terminal", 2, 40, 5, 4, "«The Linux Command Line» de William Shotts (gratis) y OverTheWire Bandit para practicar.", ["devops", "cybersecurity"]],
    ["cs50", "Hacer CS50 de Harvard (fundamentos de computación)", 4, 120, 5, 5, "Curso gratuito CS50x en edX o cs50.harvard.edu; entrega los problem sets de cada semana.", ["python", "c-lang", "algorithms"]],
    ["algorithms", "Algoritmos y estructuras de datos", 4, 150, 5, 5, "NeetCode 150 o LeetCode por temas; 1 problema al día y explícalo en voz alta.", ["cs50"]],
    ["c-lang", "Programar en C", 4, 100, 4, 4, "«The C Programming Language» de Kernighan y Ritchie; haz los ejercicios de cada capítulo.", ["embedded"]],
    ["rust", "Aprender Rust", 5, 150, 4, 4, "Lee «The Rust Programming Language» (gratis) y completa los ejercicios de Rustlings.", ["c-lang"]],
    ["go", "Aprender Go", 3, 60, 4, 4, "«A Tour of Go» oficial y luego crea una API sencilla.", ["backend", "devops"]],
    ["java", "Aprender Java", 3, 120, 4, 4, "Curso MOOC.fi «Java Programming» de la Universidad de Helsinki (gratis).", ["android"]],
    ["csharp", "Aprender C# y .NET", 3, 100, 4, 4, "Rutas gratuitas de Microsoft Learn para C#; crea una app de consola y luego una web.", ["unity"]],
    ["nodejs", "Backend con Node.js", 3, 60, 5, 5, "Documentación oficial de Node y «The Odin Project» (ruta NodeJS). Crea una API con autenticación.", ["backend", "sql"]],
    ["backend", "Diseñar APIs y backend", 4, 100, 5, 5, "Crea una API REST con autenticación, base de datos y pruebas; despliégala en un servicio gratuito.", ["sql", "devops"]],
    ["django", "Webs con Django (Python)", 3, 60, 4, 4, "Tutorial oficial de Django («Writing your first Django app») y luego un blog propio.", ["python", "sql"]],
    ["supabase", "Bases de datos en la nube con Supabase", 2, 20, 4, 4, "Guías oficiales de Supabase: autenticación, tablas y seguridad por filas (RLS).", ["sql", "nextjs"]],
    ["react-native", "Apps móviles con React Native", 4, 100, 5, 5, "Documentación de Expo; publica una app sencilla en tu móvil.", ["react", "mobile-design"]],
    ["swift", "Apps de iPhone con Swift", 4, 120, 4, 5, "Curso gratuito «100 Days of SwiftUI» de Hacking with Swift.", ["mobile-design"]],
    ["android", "Apps Android con Kotlin", 4, 120, 4, 5, "Curso oficial gratuito «Android Basics with Compose» de Google.", ["java"]],
    ["devops", "DevOps: Docker y despliegues", 4, 80, 5, 5, "Documentación de Docker y el curso gratuito «DevOps with Docker» de MOOC.fi.", ["cloud", "linux"]],
    ["cloud", "Nube: AWS, Google Cloud o Azure", 4, 120, 5, 5, "Prepara una certificación inicial (AWS Cloud Practitioner o Azure Fundamentals) con su material oficial.", ["devops"]],
    ["cybersecurity", "Ciberseguridad básica", 3, 80, 5, 5, "Rutas gratuitas de TryHackMe («Pre Security») y el curso «Google Cybersecurity».", ["linux", "networking"]],
    ["ethical-hacking", "Hacking ético y CTFs", 5, 250, 5, 5, "TryHackMe y Hack The Box Academy; participa en un CTF para principiantes (picoCTF).", ["cybersecurity"]],
    ["networking", "Redes de computadoras", 3, 80, 4, 4, "Curso gratuito de Cisco Networking Academy o la serie de redes de Professor Messer (CompTIA Network+).", ["cybersecurity", "cloud"]],
    ["automation", "Automatizar tu trabajo con scripts", 2, 30, 5, 4, "Elige 3 tareas repetitivas que hagas cada semana y automatízalas con Python o atajos del móvil.", ["python", "no-code"]],
    ["no-code", "Crear apps sin programar (no-code)", 2, 30, 4, 4, "Prueba Make o Zapier para automatizaciones y Glide o Bubble para una app simple.", ["automation", "online-business"]],
    ["game-dev", "Crear videojuegos con Godot", 3, 100, 3, 3, "Tutorial oficial «Your first 2D game» de Godot; termina un juego pequeño en vez de empezar uno grande.", ["csharp", "pixel-art"]],
    ["unity", "Crear videojuegos con Unity", 4, 150, 3, 4, "Rutas gratuitas de Unity Learn («Junior Programmer»).", ["csharp", "3d-modeling"]],
    ["open-source", "Contribuir a proyectos de código abierto", 3, 40, 4, 4, "Busca issues etiquetados «good first issue» en GitHub y envía tu primer pull request.", ["git"]],
    ["embedded", "Electrónica con Arduino", 3, 50, 4, 3, "Kit de iniciación de Arduino y sus proyectos oficiales; luego crea algo útil para tu casa.", ["c-lang", "electronics"]],
    ["raspberry", "Proyectos con Raspberry Pi", 3, 40, 4, 3, "Proyectos oficiales gratuitos en projects.raspberrypi.org; monta un servidor casero.", ["linux"]],
    ["wordpress", "Crear webs con WordPress", 2, 30, 3, 4, "Monta una web para un negocio local de práctica con un tema gratuito.", ["seo", "freelance"]],
    ["excel", "Excel o Google Sheets avanzado", 2, 30, 5, 4, "Aprende tablas dinámicas, BUSCARX y gráficos; organiza tus finanzas en una hoja.", ["data-analysis", "budgeting"]],
    ["touch-typing", "Mecanografía rápida (60+ palabras/min)", 1, 20, 4, 2, "15 minutos al día en keybr.com o monkeytype.com sin mirar el teclado.", ["writing"]],
  ],
  datos: [
    ["data-analysis", "Análisis de datos", 3, 120, 5, 5, "Certificado «Google Data Analytics» o los cursos gratuitos de Kaggle Learn (Pandas, visualización).", ["sql", "python", "excel", "statistics"]],
    ["statistics", "Estadística aplicada", 3, 80, 5, 4, "Estadística de Khan Academy y el libro «The Art of Statistics» de David Spiegelhalter.", ["data-analysis", "machine-learning"]],
    ["machine-learning", "Machine learning", 5, 200, 5, 5, "Curso «Machine Learning Specialization» de Andrew Ng (Coursera) y proyectos en Kaggle.", ["python", "statistics", "linear-algebra"]],
    ["deep-learning", "Deep learning y redes neuronales", 5, 200, 5, 5, "Curso gratuito «Practical Deep Learning for Coders» de fast.ai.", ["machine-learning"]],
    ["ai-tools", "Usar la IA para trabajar mejor", 1, 15, 5, 4, "Practica a diario con un asistente de IA: resumir, redactar, programar y planificar. Anota qué indicaciones funcionan.", ["prompting", "automation"]],
    ["prompting", "Escribir buenas instrucciones para IA", 1, 10, 5, 4, "Lee las guías de prompting de Anthropic u OpenAI y crea tu propia colección de plantillas.", ["ai-tools"]],
    ["llm-apps", "Crear aplicaciones con modelos de IA", 4, 80, 5, 5, "Documentación de la API de Claude o de OpenAI; crea un asistente que use tus propios documentos.", ["python", "javascript", "prompting"]],
    ["data-viz", "Visualización de datos", 2, 40, 4, 4, "Lee «Storytelling with Data» de Cole Nussbaumer Knaflic y rehaz 5 gráficos malos que encuentres.", ["data-analysis", "power-bi"]],
    ["power-bi", "Paneles con Power BI o Looker Studio", 2, 40, 4, 5, "Rutas gratuitas de Microsoft Learn para Power BI; crea un panel con datos públicos.", ["excel", "data-viz"]],
  ],
  diseno: [
    ["ui-design", "Diseño de interfaces (UI)", 3, 80, 5, 5, "Aprende Figma con sus tutoriales oficiales y rediseña 3 apps que uses a diario.", ["ux-design", "css", "figma"]],
    ["ux-design", "Experiencia de usuario (UX)", 3, 100, 5, 5, "Certificado «Google UX Design» o el libro «Don't Make Me Think» de Steve Krug.", ["ui-design"]],
    ["figma", "Dominar Figma", 2, 30, 5, 4, "Tutoriales oficiales de Figma y comunidades de recursos gratuitos; copia pantallas reales píxel a píxel.", ["ui-design"]],
    ["mobile-design", "Diseño de apps móviles", 3, 50, 4, 4, "Estudia las Human Interface Guidelines de Apple y Material Design de Google.", ["ui-design"]],
    ["graphic-design", "Diseño gráfico", 3, 120, 4, 4, "Aprende composición, tipografía y color; Canva para empezar y luego Affinity o Adobe.", ["typography", "branding"]],
    ["typography", "Tipografía", 2, 25, 4, 3, "Lee «Thinking with Type» de Ellen Lupton y juega con Google Fonts en tus diseños.", ["graphic-design"]],
    ["branding", "Crear identidad de marca", 3, 50, 4, 5, "Diseña logo, paleta y tono para un negocio ficticio y luego para uno real.", ["graphic-design", "marketing-digital"]],
    ["photo", "Fotografía", 2, 60, 3, 3, "Aprende exposición (ISO, apertura, velocidad) y haz una foto pensada al día durante 30 días.", ["photo-editing"]],
    ["photo-editing", "Edición de fotos (Lightroom)", 2, 30, 3, 3, "Tutoriales oficiales de Lightroom; edita 50 fotos tuyas con un estilo coherente.", ["photo"]],
    ["video-editing", "Edición de vídeo", 3, 60, 5, 5, "DaVinci Resolve (gratis) con su formación oficial; edita un vídeo corto cada semana.", ["content-creation", "motion-graphics"]],
    ["motion-graphics", "Animación y motion graphics", 4, 120, 4, 4, "After Effects o Blender; recrea animaciones que te gusten.", ["video-editing"]],
    ["3d-modeling", "Modelado 3D con Blender", 4, 150, 4, 4, "El tutorial del donut de Blender Guru en YouTube y luego modela objetos de tu casa.", ["game-dev", "3d-printing"]],
    ["illustration", "Ilustración digital", 3, 150, 3, 3, "Dibuja a diario en Krita (gratis) o Procreate; estudia anatomía y luz.", ["drawing"]],
    ["pixel-art", "Pixel art", 2, 40, 2, 2, "Aseprite o Piskel (gratis); copia sprites clásicos y luego crea los tuyos.", ["game-dev"]],
    ["interior-design", "Diseño de interiores básico", 2, 30, 3, 3, "Aprende distribución, luz y color; rediseña tu habitación con un presupuesto fijo.", ["home-organization"]],
  ],
};
