import type { IdeaArea, IdeaRow } from "./types";

export const WORK: Partial<Record<IdeaArea, IdeaRow[]>> = {
  negocios: [
    ["online-business", "Montar un pequeño negocio online", 3, 150, 5, 5, "Elige un problema concreto, valida con 10 personas antes de construir y lanza una versión mínima en 30 días.", ["marketing-digital", "sales", "copywriting"]],
    ["freelance", "Trabajar como freelance", 3, 60, 5, 5, "Define un servicio concreto, crea un portafolio con 3 trabajos y consigue tu primer cliente en tu círculo cercano.", ["negotiation", "personal-brand"]],
    ["lean-startup", "Método Lean Startup", 2, 15, 4, 5, "Lee «The Lean Startup» de Eric Ries y aplica el ciclo construir-medir-aprender a una idea tuya.", ["online-business"]],
    ["business-model", "Diseñar modelos de negocio", 2, 20, 4, 5, "Rellena el Business Model Canvas de Osterwalder para 3 empresas que admires y para tu idea.", ["lean-startup"]],
    ["ecommerce", "Tienda online (e-commerce)", 3, 60, 4, 5, "Abre una tienda de prueba en Shopify o WooCommerce y vende un producto real.", ["marketing-digital", "logistics"]],
    ["dropshipping-research", "Investigación de mercado", 2, 25, 4, 4, "Analiza la competencia, precios y reseñas de un nicho con Google Trends y marketplaces.", ["online-business"]],
    ["project-management", "Gestión de proyectos", 3, 60, 5, 5, "Certificado «Google Project Management» o la guía Scrum oficial (scrumguides.org).", ["leadership", "agile"]],
    ["agile", "Metodologías ágiles (Scrum, Kanban)", 2, 20, 4, 4, "Lee la Guía Scrum (gratis, 13 páginas) y organiza un proyecto personal con un tablero Kanban.", ["project-management"]],
    ["leadership", "Liderazgo de equipos", 4, 100, 5, 5, "Lee «The Five Dysfunctions of a Team» de Patrick Lencioni y lidera un pequeño proyecto o voluntariado.", ["communication", "feedback"]],
    ["accounting-basics", "Contabilidad básica", 3, 50, 4, 4, "Curso gratuito de contabilidad de Khan Academy o Coursera; lleva la contabilidad de un proyecto propio.", ["finance-literacy", "taxes"]],
    ["taxes", "Entender impuestos de tu país", 3, 20, 5, 4, "Lee la guía oficial de tu agencia tributaria y haz tú mismo tu próxima declaración.", ["accounting-basics"]],
    ["logistics", "Logística y cadena de suministro", 3, 60, 4, 4, "Curso introductorio «Supply Chain Management» de Coursera.", ["ecommerce"]],
    ["product-management", "Gestión de producto", 3, 80, 5, 5, "Lee «Inspired» de Marty Cagan y escribe la estrategia de producto de una app que uses.", ["ux-design", "data-analysis"]],
    ["pitching", "Presentar ideas a inversores", 3, 20, 4, 5, "Prepara un pitch de 3 minutos y preséntalo a 5 personas pidiendo crítica sincera.", ["public-speaking", "storytelling"]],
    ["real-estate", "Inversión inmobiliaria básica", 4, 80, 4, 5, "Aprende a calcular rentabilidad, hipotecas y costes; analiza 20 anuncios reales en una hoja.", ["finance-literacy", "negotiation"]],
  ],
  finanzas: [
    ["finance-literacy", "Educación financiera básica", 1, 15, 5, 4, "Lee «El hombre más rico de Babilonia» de George S. Clason y aplica «págate primero a ti».", ["budgeting", "investing"]],
    ["budgeting", "Hacer y seguir un presupuesto", 1, 8, 5, 4, "Registra cada gasto durante 30 días y crea un presupuesto con la regla 50/30/20 como punto de partida.", ["emergency-fund", "excel"]],
    ["emergency-fund", "Crear un fondo de emergencia", 1, 5, 5, 3, "Calcula tus gastos de 3-6 meses y automatiza una transferencia mensual a una cuenta aparte.", ["budgeting"]],
    ["investing", "Invertir a largo plazo (fondos indexados)", 2, 30, 5, 5, "Lee «The Little Book of Common Sense Investing» de John C. Bogle y entiende comisiones, diversificación e interés compuesto.", ["finance-literacy", "retirement"]],
    ["intelligent-investor", "Leer «El inversor inteligente» (Benjamin Graham)", 4, 25, 4, 4, "Lee la edición comentada por Jason Zweig, un capítulo por semana, con notas.", ["investing"]],
    ["psychology-money", "Leer «La psicología del dinero» (Morgan Housel)", 1, 7, 5, 3, "Un capítulo al día; escribe qué cambiarías en tu forma de gastar.", ["finance-literacy"]],
    ["retirement", "Planificar tu jubilación", 2, 10, 5, 4, "Calcula cuánto necesitas con un simulador oficial de tu país y fija un ahorro mensual.", ["investing"]],
    ["debt-free", "Salir de deudas", 2, 10, 5, 4, "Lista tus deudas por interés y aplica el método avalancha o bola de nieve.", ["budgeting"]],
    ["side-income", "Crear un ingreso extra", 3, 80, 5, 5, "Elige una habilidad que ya tengas y ofrécela en una plataforma o a tu red durante 4 semanas.", ["freelance", "online-business"]],
    ["crypto-basics", "Entender blockchain y criptomonedas (con cautela)", 3, 20, 3, 3, "Lee el whitepaper de Bitcoin y fuentes neutrales; entiende los riesgos antes de invertir nada.", ["investing"]],
    ["financial-statements", "Leer estados financieros", 3, 30, 4, 4, "Analiza el informe anual de una empresa que conozcas: balance, resultados y flujo de caja.", ["accounting-basics", "investing"]],
  ],
  marketing: [
    ["marketing-digital", "Marketing digital", 3, 80, 5, 5, "Curso gratuito «Fundamentos de Marketing Digital» de Google Actívate.", ["seo", "copywriting", "social-media"]],
    ["seo", "Posicionamiento en buscadores (SEO)", 3, 50, 4, 5, "Guía para principiantes de SEO de Google Search Central; posiciona un artículo propio.", ["writing", "marketing-digital"]],
    ["copywriting", "Copywriting (escribir para vender)", 3, 60, 5, 5, "Lee «Influence» de Robert Cialdini y reescribe 10 anuncios o páginas que veas.", ["writing", "sales"]],
    ["social-media", "Gestión de redes sociales", 2, 40, 4, 4, "Gestiona durante un mes una cuenta con calendario de contenido y métricas.", ["content-creation"]],
    ["content-creation", "Crear contenido (YouTube, TikTok, blog)", 3, 150, 5, 5, "Publica una pieza por semana durante 12 semanas sobre algo que estés aprendiendo.", ["video-editing", "storytelling", "personal-brand"]],
    ["personal-brand", "Construir tu marca personal", 3, 60, 5, 5, "Define tu tema, optimiza tu perfil de LinkedIn y comparte lo que aprendes cada semana.", ["content-creation", "networking-pro"]],
    ["sales", "Ventas", 3, 80, 5, 5, "Lee «SPIN Selling» de Neil Rackham y practica preguntas de descubrimiento en conversaciones reales.", ["negotiation", "communication"]],
    ["email-marketing", "Email marketing", 2, 25, 4, 5, "Crea una lista con un servicio gratuito y envía un boletín cada dos semanas.", ["copywriting"]],
    ["ads", "Publicidad pagada (Google y Meta Ads)", 3, 40, 4, 5, "Certificaciones gratuitas de Google Ads; lanza una campaña de prueba con 5 € al día.", ["marketing-digital", "data-analysis"]],
    ["podcasting", "Crear un pódcast", 2, 40, 3, 3, "Graba 5 episodios de prueba con tu móvil antes de comprar equipo.", ["public-speaking", "content-creation"]],
  ],
  oficios: [
    ["carpentry", "Carpintería básica", 3, 120, 4, 4, "Curso presencial en un centro de formación o makerspace; construye una estantería y una mesa sencilla.", ["woodworking-tools", "diy-home"]],
    ["woodworking-tools", "Uso seguro de herramientas eléctricas", 2, 15, 4, 3, "Aprende con supervisión: taladro, sierra de calar y lijadora. Equipo de protección siempre.", ["carpentry"]],
    ["electricity-home", "Electricidad doméstica básica", 3, 40, 4, 4, "Curso de iniciación; aprende a cambiar enchufes e interruptores con la corriente cortada. Lo complejo, siempre un profesional.", ["diy-home"]],
    ["plumbing", "Fontanería básica", 2, 20, 4, 3, "Aprende a cambiar un grifo, desatascar y reparar una cisterna con tutoriales y práctica guiada.", ["diy-home"]],
    ["diy-home", "Reparaciones del hogar", 2, 40, 5, 3, "Arregla una cosa de tu casa cada semana: bisagras, pintura, silicona, muebles.", ["carpentry", "plumbing"]],
    ["welding", "Soldadura", 4, 150, 4, 5, "Curso oficial de soldadura en un centro de formación profesional.", ["metalwork"]],
    ["metalwork", "Trabajo del metal", 4, 120, 3, 4, "Curso en un taller o makerspace con supervisión.", ["welding"]],
    ["mechanics", "Mecánica básica del coche", 3, 40, 4, 3, "Aprende a cambiar aceite, filtros, ruedas y revisar frenos con el manual de tu coche.", ["diy-home"]],
    ["bike-repair", "Reparar bicicletas", 2, 20, 3, 2, "Guías de reparación de Park Tool; aprende a cambiar cámara, frenos y cadena.", ["mechanics"]],
    ["sewing", "Costura y arreglos de ropa", 2, 40, 4, 3, "Empieza con dobladillos y botones a mano; luego máquina de coser con patrones sencillos.", ["upcycling"]],
    ["upcycling", "Restaurar y reutilizar muebles", 2, 30, 3, 3, "Restaura un mueble usado: lijar, reparar y pintar.", ["carpentry"]],
    ["3d-printing", "Impresión 3D", 3, 40, 4, 4, "Modela piezas útiles en Tinkercad o Fusion y imprímelas en un makerspace.", ["3d-modeling"]],
    ["electronics", "Electrónica y soldadura de componentes", 3, 50, 4, 3, "Kit de iniciación con soldador; repara un aparato roto.", ["embedded"]],
    ["gardening-pro", "Jardinería y paisajismo", 2, 60, 3, 3, "Cultiva un huerto pequeño y aprende poda y riego.", ["vegetable-garden"]],
    ["barbering", "Barbería y corte de pelo", 3, 150, 3, 4, "Curso presencial; practica con familiares y amigos.", []],
    ["locksmith-basics", "Instalar y cambiar cerraduras", 2, 10, 3, 2, "Cambia el bombín de una puerta siguiendo las instrucciones del fabricante.", ["diy-home"]],
    ["ceramics", "Cerámica y torno", 3, 80, 2, 3, "Taller de cerámica en tu ciudad; empieza con modelado a mano.", ["drawing"]],
    ["leatherwork", "Marroquinería (trabajo en cuero)", 3, 40, 2, 3, "Haz una cartera sencilla con un kit de iniciación.", []],
    ["tiling-painting", "Pintar paredes y alicatar", 2, 20, 3, 3, "Pinta una habitación con preparación correcta: cinta, imprimación y dos manos.", ["diy-home"]],
  ],
};
