import type { IdeaArea, IdeaRow } from "./types";

export const LIFE: Partial<Record<IdeaArea, IdeaRow[]>> = {
  social: [
    ["communication", "Comunicación efectiva", 2, 30, 5, 5, "Practica la escucha activa: resume lo que te dicen antes de responder durante una semana.", ["public-speaking", "feedback"]],
    ["public-speaking", "Hablar en público", 3, 40, 5, 5, "Únete a un club Toastmasters o graba un discurso de 5 minutos cada semana.", ["storytelling", "confidence"]],
    ["negotiation", "Negociación", 3, 30, 5, 5, "Lee «Nunca dividas la diferencia» de Chris Voss y negocia algo pequeño cada semana.", ["sales", "communication"]],
    ["social-skills", "Habilidades sociales", 2, 30, 5, 4, "Empieza una conversación con alguien nuevo cada día durante un mes.", ["confidence", "networking-pro"]],
    ["confidence", "Seguridad en ti mismo", 3, 30, 5, 4, "Lista de retos de incomodidad progresivos; haz uno cada día.", ["social-skills"]],
    ["networking-pro", "Crear una red de contactos profesional", 2, 30, 5, 5, "Escribe a 2 personas por semana que admires con una pregunta concreta.", ["personal-brand"]],
    ["empathy", "Empatía", 2, 20, 5, 2, "Lee «Comunicación no violenta» de Marshall Rosenberg y practica sus 4 pasos.", ["communication"]],
    ["feedback", "Dar y recibir feedback", 2, 15, 5, 4, "Pide una crítica concreta cada semana y agradécela sin justificarte.", ["leadership"]],
    ["debate", "Debate y argumentación", 3, 40, 4, 3, "Únete a un club de debate o escribe argumentos a favor y en contra de un tema cada semana.", ["critical-thinking"]],
    ["conflict", "Resolver conflictos", 3, 20, 5, 3, "Aprende el método de Harvard: separar personas del problema e intereses de posiciones.", ["negotiation", "empathy"]],
    ["dating", "Relaciones de pareja sanas", 2, 20, 5, 1, "Lee «Los 5 lenguajes del amor» de Gary Chapman o «Maestros del amor» de John Gottman.", ["empathy"]],
    ["mentoring", "Ser mentor de alguien", 3, 40, 4, 2, "Ofrece una hora al mes a alguien que va unos pasos detrás de ti.", ["leadership", "teaching"]],
    ["teaching", "Enseñar lo que sabes", 3, 50, 5, 4, "Da una clase o tutoría gratuita sobre algo que domines; explicar consolida lo aprendido.", ["mentoring", "public-speaking"]],
    ["sign-language", "Lengua de signos", 3, 120, 4, 3, "Curso oficial de la lengua de signos de tu país.", ["empathy"]],
  ],
  familia: [
    ["parenting", "Crianza consciente", 3, 40, 5, 1, "Lee «Cómo hablar para que los niños escuchen» de Faber y Mazlish.", ["empathy"]],
    ["family-time", "Tiempo de calidad en familia", 1, 50, 5, 1, "Una comida por semana sin pantallas y una actividad mensual juntos.", []],
    ["family-history", "Investigar la historia de tu familia", 2, 30, 3, 1, "Entrevista a tus mayores, graba sus historias y crea un árbol genealógico.", ["writing"]],
    ["home-organization", "Organización del hogar", 1, 15, 4, 2, "Una zona por semana: vaciar, limpiar, decidir y ordenar.", ["minimalism"]],
    ["home-finance-family", "Finanzas familiares", 2, 15, 5, 3, "Reunión mensual de presupuesto en casa con metas compartidas.", ["budgeting"]],
    ["elder-care", "Cuidar de mayores", 3, 30, 5, 2, "Aprende primeros auxilios, movilidad y paciencia; pregunta en tu centro de salud.", ["first-aid", "empathy"]],
    ["pet-training", "Educar a tu mascota", 2, 30, 3, 1, "Refuerzo positivo con sesiones de 5 minutos al día.", []],
    ["housekeeping", "Rutina de limpieza eficiente", 1, 10, 4, 1, "Rutina de 15 minutos diaria por zonas para no acumular.", ["home-organization"]],
  ],
  cocina: [
    ["cooking-basics", "Cocina básica (10 recetas)", 1, 20, 5, 2, "Aprende 10 platos sanos y baratos que puedas repetir cada semana.", ["meal-prep", "nutrition"]],
    ["meal-prep", "Cocinar para toda la semana", 2, 10, 5, 3, "Domingo de 2 horas: cocina bases (grano, proteína, verdura) para 4 días.", ["cooking-basics"]],
    ["knife-skills", "Técnica de cuchillo", 2, 10, 4, 2, "Practica cortes básicos (juliana, brunoise) con vídeos de escuelas de cocina.", ["cooking-basics"]],
    ["baking-bread", "Hacer pan casero", 2, 20, 3, 2, "Empieza con un pan sin amasado y luego masa madre.", ["cooking-basics"]],
    ["pastry", "Repostería", 3, 50, 2, 3, "Domina 5 bases: bizcocho, masa quebrada, crema pastelera, merengue y galletas.", ["baking-bread"]],
    ["chinese-cooking", "Cocina china casera", 2, 30, 2, 1, "Aprende el salteado en wok y 5 platos clásicos.", ["lang-chinese-a1"]],
    ["mexican-cooking", "Cocina mexicana tradicional", 2, 30, 2, 2, "Salsas, tortillas, moles sencillos y antojitos.", ["cooking-basics"]],
    ["fermentation", "Fermentados (kimchi, kéfir, chucrut)", 2, 15, 3, 1, "Haz un chucrut con col y sal y sigue normas de higiene.", ["nutrition"]],
    ["coffee", "Café de especialidad en casa", 1, 10, 2, 2, "Aprende molienda, proporción y métodos de filtrado.", []],
  ],
  ciencia: [
    ["math-foundations", "Matemáticas básicas sólidas", 2, 80, 5, 3, "Repasa aritmética, álgebra y porcentajes en Khan Academy hasta dominar cada unidad.", ["algebra", "statistics"]],
    ["algebra", "Álgebra", 3, 60, 5, 3, "Unidades de álgebra de Khan Academy; haz los ejercicios hasta dominarlos.", ["calculus"]],
    ["calculus", "Cálculo", 4, 120, 4, 4, "Serie «Essence of Calculus» de 3Blue1Brown y ejercicios de Khan Academy.", ["linear-algebra", "physics"]],
    ["linear-algebra", "Álgebra lineal", 4, 80, 5, 4, "Serie «Essence of Linear Algebra» de 3Blue1Brown y MIT OCW 18.06.", ["machine-learning"]],
    ["probability", "Probabilidad", 3, 50, 5, 4, "Curso de probabilidad de Khan Academy y problemas diarios.", ["statistics"]],
    ["physics", "Física general", 4, 120, 4, 3, "«Física» de Khan Academy o las «Lecciones de física» de Feynman.", ["calculus"]],
    ["chemistry", "Química general", 3, 100, 3, 3, "Química de Khan Academy o Crash Course Chemistry.", ["biology"]],
    ["biology", "Biología", 3, 100, 4, 3, "Biología de Khan Academy; relaciona cada tema con tu salud.", ["nutrition"]],
    ["astronomy", "Astronomía", 2, 40, 2, 1, "Aprende constelaciones con Stellarium (gratis) y observa el cielo una noche al mes.", ["physics"]],
    ["economics", "Economía", 3, 60, 5, 4, "Macroeconomía y microeconomía de Khan Academy.", ["investing", "finance-literacy"]],
    ["psychology", "Psicología", 3, 60, 4, 3, "Curso «Introduction to Psychology» de Yale (Coursera).", ["emotional-intelligence"]],
    ["neuroscience", "Neurociencia básica", 3, 40, 3, 2, "Lee «El cerebro» de David Eagleman o Crash Course Psychology.", ["psychology"]],
    ["climate", "Ciencia del clima", 2, 25, 4, 2, "Lee los resúmenes para responsables de políticas del IPCC.", ["sustainability"]],
    ["olympiad-math", "Problemas de olimpiada matemática", 5, 200, 3, 2, "Libros de problemas y el sitio Art of Problem Solving.", ["algebra"]],
  ],
  naturaleza: [
    ["vegetable-garden", "Huerto urbano", 2, 40, 4, 2, "Empieza con 3 macetas: lechuga, tomate y hierbas aromáticas.", ["gardening-pro", "composting"]],
    ["composting", "Compostaje", 1, 8, 3, 1, "Compostera pequeña con restos de cocina y hojas secas.", ["vegetable-garden"]],
    ["camping", "Acampada y vida al aire libre", 2, 30, 3, 1, "Acampada de una noche en camping antes de ir a zonas aisladas.", ["hiking", "survival"]],
    ["survival", "Supervivencia básica", 3, 30, 3, 1, "Curso de supervivencia: agua, refugio, fuego y orientación.", ["camping", "orientation"]],
    ["orientation", "Orientación con mapa y brújula", 2, 15, 3, 1, "Practica en carreras de orientación de tu zona.", ["hiking"]],
    ["birdwatching", "Observación de aves", 1, 20, 2, 1, "Usa una guía de campo o la app Merlin y sal una mañana al mes.", []],
    ["sustainability", "Vida sostenible", 2, 20, 5, 2, "Mide tu huella de carbono y elige 3 cambios.", ["climate", "minimalism"]],
    ["fishing", "Pesca", 2, 30, 2, 1, "Saca la licencia y aprende con alguien con experiencia.", []],
  ],
  servicio: [
    ["volunteering", "Voluntariado", 1, 50, 5, 1, "Elige una causa y dedica 2 horas al mes en una organización local.", ["empathy", "first-aid"]],
    ["blood-donation", "Donar sangre con regularidad", 1, 3, 5, 1, "Consulta requisitos y dona cada pocos meses si puedes.", ["volunteering"]],
    ["civic", "Entender tu sistema político y tus derechos", 2, 20, 4, 1, "Lee la constitución de tu país y sigue las noticias en 2 medios distintos.", ["political-philosophy"]],
    ["driving", "Sacar el carné de conducir", 3, 50, 5, 3, "Autoescuela: teórico con tests diarios y prácticas regulares.", ["mechanics"]],
    ["self-defense-legal", "Conocer derechos laborales", 2, 10, 5, 4, "Lee el convenio de tu sector y tu contrato completo.", ["negotiation"]],
  ],
  habitos: [
    ["morning-routine", "Rutina de mañana", 1, 10, 5, 3, "Despertar a hora fija, agua, movimiento y tu tarea más importante antes del móvil.", ["sleep", "habit-building"]],
    ["evening-review", "Revisión de cada noche", 1, 10, 5, 3, "5 minutos: qué hiciste, qué aprendiste y las 3 tareas de mañana.", ["journaling", "time-management"]],
    ["weekly-review", "Revisión semanal", 1, 10, 5, 4, "Cada domingo, 30 minutos: revisa objetivos, agenda y pendientes.", ["gtd"]],
    ["cold-shower", "Ducha fría", 1, 2, 3, 1, "Termina la ducha con 30 segundos de agua fría y sube poco a poco.", ["discipline"]],
    ["walk-daily", "Caminar 8 000 pasos al día", 1, 50, 5, 1, "Haz llamadas caminando y baja una parada antes.", ["mobility"]],
    ["water", "Beber suficiente agua", 1, 2, 4, 1, "Botella visible en tu mesa y un vaso con cada comida.", ["nutrition"]],
    ["no-phone-morning", "Primera hora sin móvil", 2, 5, 5, 3, "Deja el móvil fuera del dormitorio y usa un despertador.", ["digital-detox"]],
    ["one-thing", "Una tarea importante al día", 1, 5, 5, 4, "Cada mañana decide la tarea que haría el día un éxito y empieza por ella.", ["focus-deep-work"]],
  ],
};
