import type { IdeaArea, IdeaRow } from "./types";

/** Más ideas para inspirarte, repartidas por áreas. */
export const MORE: Partial<Record<IdeaArea, IdeaRow[]>> = {
  negocios: [
    ["strategy", "Pensamiento estratégico", 3, 30, 5, 5, "Lee «Good Strategy Bad Strategy» de Richard Rumelt y escribe el diagnóstico, la política y las acciones de un objetivo tuyo.", ["leadership", "business-model"]],
    ["customer-service", "Atención al cliente excelente", 2, 20, 4, 4, "Escribe guiones para las 10 situaciones más comunes y practica con alguien.", ["communication", "empathy"]],
    ["franchise-study", "Estudiar cómo funcionan las franquicias", 2, 15, 3, 4, "Analiza los costes y contratos de 3 franquicias reales de tu ciudad.", ["business-model"]],
    ["hiring", "Seleccionar y contratar personas", 3, 30, 4, 4, "Lee «Who» de Geoff Smart y Randy Street; diseña una entrevista estructurada.", ["leadership"]],
    ["okrs", "Fijar objetivos con OKR", 2, 10, 4, 4, "Lee «Mide lo que importa» de John Doerr y define 3 OKR personales para este trimestre.", ["project-management"]],
    ["unit-economics", "Economía unitaria de un negocio", 3, 20, 4, 5, "Calcula coste de adquisición, margen y valor de vida del cliente de una empresa que conozcas.", ["accounting-basics", "online-business"]],
  ],
  tecnologia: [
    ["regex", "Expresiones regulares", 2, 10, 4, 3, "Tutorial interactivo de RegexOne y practica en regex101.com.", ["python", "javascript"]],
    ["accessibility", "Accesibilidad web", 2, 25, 5, 4, "Guías WAI del W3C; revisa una web tuya con un lector de pantalla.", ["html", "ux-design"]],
    ["testing", "Pruebas automáticas de software", 3, 40, 5, 4, "Escribe pruebas para un proyecto tuyo con Vitest o pytest hasta cubrir la lógica principal.", ["javascript", "python"]],
    ["system-design", "Diseño de sistemas", 5, 120, 5, 5, "Lee «Designing Data-Intensive Applications» de Martin Kleppmann.", ["backend", "cloud"]],
    ["chrome-extension", "Crear una extensión de navegador", 2, 20, 3, 3, "Documentación oficial de extensiones de Chrome; resuelve una molestia tuya.", ["javascript"]],
    ["bots", "Crear un bot de Telegram o Discord", 2, 20, 3, 3, "Usa la API oficial y Python o Node; empieza con un bot que te recuerde tareas.", ["python", "nodejs"]],
    ["pc-building", "Montar tu propio ordenador", 2, 10, 3, 2, "Elige piezas compatibles con PCPartPicker y móntalo siguiendo una guía.", ["electronics"]],
    ["web-scraping", "Extraer datos de webs (scraping)", 3, 25, 4, 4, "Python con requests y BeautifulSoup respetando los términos de cada sitio.", ["python", "data-analysis"]],
    ["blockchain-dev", "Programar contratos inteligentes", 4, 100, 3, 4, "Documentación de Ethereum y Solidity; despliega en una red de pruebas.", ["javascript", "crypto-basics"]],
    ["quantum-basics", "Computación cuántica básica", 5, 80, 3, 3, "Curso gratuito de IBM Quantum Learning.", ["linear-algebra"]],
  ],
  salud: [
    ["boxing", "Boxeo", 3, 80, 3, 1, "Clases en un gimnasio de boxeo; técnica antes que sparring.", ["martial-arts"]],
    ["pilates", "Pilates", 2, 40, 4, 1, "Clases para principiantes 2 veces por semana.", ["posture", "mobility"]],
    ["handstand", "Hacer el pino (handstand)", 4, 60, 2, 1, "10 minutos al día contra la pared con progresiones.", ["calisthenics"]],
    ["triathlon", "Completar un triatlón sprint", 4, 120, 3, 1, "Plan de 12 semanas combinando natación, bici y carrera.", ["swimming", "cycling", "running-5k"]],
    ["surf", "Surf", 3, 60, 2, 1, "Escuela de surf con clases de iniciación.", ["swimming"]],
    ["skiing", "Esquí o snowboard", 3, 40, 2, 1, "Clases de iniciación el primer viaje.", []],
    ["healthy-weight", "Llegar a un peso saludable", 3, 50, 5, 2, "Consulta a un profesional sanitario; registra comida y pasos durante un mes.", ["nutrition", "walk-daily"]],
    ["breathing", "Técnicas de respiración", 1, 5, 4, 1, "Respiración diafragmática y 4-7-8 cinco minutos al día.", ["stress-management"]],
  ],
  mente: [
    ["note-taking", "Tomar buenas notas (segundo cerebro)", 2, 15, 5, 4, "Lee «Building a Second Brain» de Tiago Forte y organiza tus notas en Notion u Obsidian.", ["gtd", "writing"]],
    ["mental-models", "Modelos mentales", 3, 30, 5, 4, "Lee el blog Farnam Street o «The Great Mental Models»; aplica uno a cada decisión importante.", ["critical-thinking"]],
    ["decision-making", "Tomar mejores decisiones", 3, 20, 5, 4, "Lee «Thinking in Bets» de Annie Duke y lleva un diario de decisiones.", ["probability"]],
    ["resilience", "Resiliencia", 3, 20, 5, 2, "Escribe cómo superaste 3 momentos difíciles y qué recursos usaste.", ["stoicism"]],
    ["procrastination", "Vencer la procrastinación", 2, 10, 5, 4, "Regla de los 2 minutos y bloques Pomodoro; empieza por lo más pequeño.", ["habit-building"]],
    ["mental-math", "Cálculo mental", 2, 20, 3, 2, "10 minutos al día de ejercicios de cálculo mental.", ["math-foundations"]],
    ["rubiks", "Resolver el cubo de Rubik", 2, 10, 1, 1, "Aprende el método por capas para principiantes.", []],
    ["go-game", "Jugar al go (weiqi)", 4, 150, 2, 1, "Tutorial interactivo de online-go.com y partidas en tableros pequeños de 9x9.", ["chess", "lang-chinese-a1"]],
  ],
  lectura: [
    ["the-prince", "Leer «El príncipe» de Maquiavelo", 2, 4, 3, 2, "Léelo con su contexto histórico; resume cada capítulo en una frase.", ["political-philosophy"]],
    ["siddhartha", "Leer «Siddhartha» de Hermann Hesse", 2, 4, 3, 1, "Léelo en una semana y escribe qué aprendió Siddhartha del río.", ["eastern-philosophy"]],
    ["the-stranger", "Leer «El extranjero» de Albert Camus", 2, 4, 3, 1, "Léelo de una sentada y compáralo con «El mito de Sísifo».", ["existentialism"]],
    ["the-trial", "Leer «El proceso» de Franz Kafka", 3, 7, 3, 1, "Un capítulo al día y anota lo que te resulte absurdo.", ["literature"]],
    ["metamorphosis", "Leer «La metamorfosis» de Kafka", 2, 2, 3, 1, "Léela en una tarde y piensa qué te dice sobre el trabajo y la familia.", ["literature"]],
    ["pedro-paramo", "Leer «Pedro Páramo» de Juan Rulfo", 3, 3, 3, 1, "Léelo dos veces: la segunda entenderás mucho más.", ["spanish-literature"]],
    ["ficciones", "Leer «Ficciones» de Jorge Luis Borges", 4, 5, 3, 1, "Un cuento por día; relee «El jardín de senderos que se bifurcan».", ["spanish-literature"]],
    ["the-alchemist", "Leer «El alquimista» de Paulo Coelho", 1, 4, 3, 1, "Léelo en una semana; anota tu «leyenda personal».", ["purpose"]],
    ["essays-montaigne", "Leer los «Ensayos» de Montaigne (selección)", 3, 15, 3, 1, "Un ensayo por semana y escribe tu propio ensayo breve.", ["writing", "philosophy-intro"]],
    ["on-friendship-cicero", "Leer «Sobre la amistad» de Cicerón", 2, 2, 3, 1, "Léelo en una tarde y piensa en tus amistades.", ["social-skills"]],
    ["zero-to-one", "Leer «De cero a uno» de Peter Thiel", 2, 5, 4, 4, "Responde la pregunta del libro: ¿qué verdad importante pocos comparten contigo?", ["online-business"]],
    ["the-mom-test", "Leer «The Mom Test» de Rob Fitzpatrick", 1, 3, 4, 5, "Antes de lanzar una idea, entrevista a 5 personas con su método.", ["lean-startup"]],
    ["essentialism", "Leer «Esencialismo» de Greg McKeown", 1, 6, 5, 3, "Elimina un compromiso que no sea esencial cada semana.", ["time-management"]],
    ["mastery-greene", "Leer «Maestría» de Robert Greene", 3, 12, 4, 4, "Identifica tu área de maestría y a quién podrías tener de mentor.", ["purpose"]],
    ["outliers", "Leer «Fuera de serie (Outliers)» de Malcolm Gladwell", 1, 7, 4, 2, "Léelo con espíritu crítico sobre la «regla de las 10 000 horas».", ["deliberate-practice"]],
    ["peak-ericsson", "Leer «Peak» de Anders Ericsson", 2, 8, 5, 4, "El libro del autor original sobre práctica deliberada; diseña tu plan de práctica.", ["deliberate-practice"]],
    ["the-odyssey-iliad", "Leer «La Ilíada» de Homero", 4, 18, 3, 1, "Un canto cada dos días; repasa los personajes antes de empezar.", ["odyssey"]],
    ["letters-young-poet", "Leer «Cartas a un joven poeta» de Rilke", 2, 2, 3, 1, "Una carta por día y escribe tu respuesta.", ["poetry-reading"]],
  ],
  cultura: [
    ["opera", "Descubrir la ópera", 2, 20, 2, 1, "Escucha una ópera al mes con el libreto: empieza por «La Traviata» o «Carmen».", ["music-theory"]],
    ["architecture", "Historia de la arquitectura", 3, 30, 2, 1, "Visita y estudia 10 edificios importantes de tu ciudad.", ["art-history"]],
    ["photography-history", "Grandes fotógrafos", 2, 15, 2, 1, "Estudia a Cartier-Bresson, Dorothea Lange y Sebastião Salgado.", ["photo"]],
    ["comics", "Crear cómic o novela gráfica", 3, 100, 2, 2, "Lee «Entender el cómic» de Scott McCloud y dibuja una historia de 4 páginas.", ["drawing", "storytelling"]],
    ["improv", "Improvisación teatral", 2, 30, 4, 2, "Taller de impro; mejora la escucha y la rapidez mental.", ["confidence", "public-speaking"]],
    ["stand-up", "Comedia (stand-up)", 3, 50, 3, 3, "Escribe 5 minutos de material y pruébalo en un micro abierto.", ["public-speaking", "writing"]],
    ["film-making", "Hacer un cortometraje", 3, 60, 3, 3, "Guion de 3 páginas, rodaje con móvil y edición propia.", ["video-editing", "storytelling"]],
    ["wine-culture", "Cultura del vino y la gastronomía (con moderación)", 2, 20, 2, 2, "Cata guiada y aprende regiones y maridajes.", ["cooking-basics"]],
    ["tea-culture", "Cultura del té", 1, 10, 2, 1, "Aprende tipos de té y la ceremonia china gongfu cha.", ["history-china"]],
  ],
  musica: [
    ["violin", "Tocar el violín", 4, 300, 2, 2, "Profesor desde el inicio; 20 minutos diarios.", ["music-theory", "ear-training"]],
    ["harmonica", "Tocar la armónica", 2, 30, 1, 1, "Armónica diatónica en Do y canciones populares sencillas.", []],
    ["songwriting", "Componer canciones", 3, 80, 2, 2, "Escribe una canción completa al mes, aunque sea sencilla.", ["guitar", "poetry-writing"]],
  ],
  social: [
    ["interview-skills", "Hacer entrevistas de trabajo brillantes", 2, 15, 5, 5, "Prepara historias con el método STAR y haz entrevistas simuladas.", ["communication", "storytelling"]],
    ["cv-linkedin", "CV y LinkedIn profesionales", 1, 8, 5, 5, "Reescribe tu CV con logros medibles y actualiza tu perfil.", ["personal-brand"]],
    ["hosting", "Organizar reuniones y eventos", 2, 20, 4, 3, "Organiza una cena o actividad al mes para tu grupo.", ["social-skills"]],
    ["small-talk", "Conversación informal (small talk)", 1, 10, 4, 3, "Prepara 5 preguntas abiertas y úsalas esta semana.", ["social-skills"]],
    ["persuasion", "Persuasión ética", 3, 30, 5, 5, "Lee «Influence» de Robert Cialdini y analiza un anuncio con sus 6 principios.", ["sales", "copywriting"]],
  ],
  ciencia: [
    ["geometry", "Geometría", 3, 50, 3, 2, "Geometría de Khan Academy y problemas de construcción con regla y compás.", ["math-foundations"]],
    ["number-theory", "Teoría de números", 4, 60, 3, 2, "Libro introductorio de teoría de números y problemas diarios.", ["olympiad-math"]],
    ["discrete-math", "Matemática discreta", 4, 80, 5, 4, "MIT OCW «Mathematics for Computer Science».", ["algorithms", "logic"]],
    ["game-theory", "Teoría de juegos", 3, 40, 4, 4, "Curso «Game Theory» de Stanford y la Universidad de Columbia Británica en Coursera.", ["economics", "negotiation"]],
    ["anatomy", "Anatomía humana básica", 3, 50, 4, 2, "Atlas de anatomía y apps 3D; relaciónalo con tu entrenamiento.", ["biology", "strength-training"]],
    ["geology", "Geología", 2, 30, 2, 1, "Curso introductorio y sal a identificar rocas en una excursión.", ["hiking"]],
    ["electrical-engineering", "Circuitos eléctricos", 4, 100, 4, 4, "MIT OCW «Circuits and Electronics» (6.002).", ["electronics", "physics"]],
  ],
  finanzas: [
    ["negotiate-salary", "Negociar tu salario", 2, 8, 5, 5, "Investiga sueldos de mercado y ensaya la conversación con alguien.", ["negotiation"]],
    ["insurance", "Entender seguros", 2, 8, 4, 3, "Revisa tus pólizas y compara coberturas reales.", ["finance-literacy"]],
    ["frugal", "Ahorrar sin sufrir (frugalidad)", 1, 8, 5, 4, "Revisa suscripciones y gastos fijos y recorta los que no te aportan.", ["budgeting"]],
  ],
  familia: [
    ["kids-education", "Ayudar a estudiar a niños", 2, 30, 4, 2, "Rutina fija de estudio, preguntas en vez de respuestas y lectura compartida.", ["teaching"]],
    ["wedding-planning", "Organizar un gran evento familiar", 3, 60, 2, 2, "Hoja con presupuesto, tareas y fechas; delega por áreas.", ["project-management"]],
  ],
  naturaleza: [
    ["foraging", "Identificar plantas silvestres", 3, 40, 2, 1, "Guía de campo de tu región; nunca comas nada sin certeza absoluta.", ["hiking"]],
    ["sailing", "Navegación a vela", 3, 60, 2, 1, "Curso de iniciación en un club náutico.", ["swimming"]],
    ["beekeeping", "Apicultura", 3, 60, 2, 2, "Curso de apicultura y visita a un colmenar con un apicultor.", ["vegetable-garden"]],
    ["aquarium", "Montar un acuario", 2, 20, 1, 1, "Aprende el ciclo del nitrógeno antes de comprar peces.", []],
  ],
  servicio: [
    ["emergency-prep", "Preparación ante emergencias", 1, 8, 5, 1, "Prepara un kit de emergencia y un plan familiar.", ["first-aid"]],
    ["ngo", "Fundar o colaborar en una asociación", 3, 80, 4, 2, "Únete a la junta de una asociación de tu barrio o crea una con un objetivo concreto.", ["leadership", "volunteering"]],
  ],
  habitos: [
    ["deliberate-practice", "Práctica deliberada en tu habilidad principal", 3, 100, 5, 5, "Sesiones cortas en el borde de tu capacidad, con feedback inmediato y un objetivo concreto cada vez.", ["peak-ericsson"]],
    ["daily-learning", "30 minutos de aprendizaje al día", 1, 180, 5, 4, "Bloque fijo en tu horario para estudiar una habilidad elegida.", ["deliberate-practice"]],
    ["inbox-zero", "Bandeja de entrada a cero", 1, 5, 4, 3, "Procesa el correo 2 veces al día: borrar, archivar, responder o planificar.", ["gtd"]],
    ["screen-time", "Reducir el tiempo de pantalla a la mitad", 2, 10, 5, 2, "Mira tu tiempo de uso actual y pon límites a las 3 apps que más usas.", ["digital-detox"]],
  ],
};
