import type { IdeaArea, IdeaRow } from "./types";

export const SELF: Partial<Record<IdeaArea, IdeaRow[]>> = {
  salud: [
    ["strength-training", "Entrenamiento de fuerza", 2, 60, 5, 2, "3 sesiones por semana con básicos (sentadilla, peso muerto, press, remo) y progresión lenta; pide a alguien que revise tu técnica.", ["nutrition", "sleep"]],
    ["running-5k", "Correr 5 km sin parar", 2, 20, 5, 1, "Programa de 9 semanas tipo «Couch to 5K», 3 días por semana.", ["running-10k"]],
    ["running-10k", "Correr 10 km", 3, 40, 4, 1, "Tras los 5 km, añade un rodaje largo semanal que crezca un 10 % cada semana.", ["running-5k", "half-marathon"]],
    ["half-marathon", "Correr una media maratón", 4, 80, 3, 1, "Plan de 12-16 semanas con 4 días de carrera; inscríbete a una carrera para tener fecha.", ["running-10k"]],
    ["swimming", "Nadar bien (técnica de crol)", 3, 40, 4, 2, "Clases en tu piscina municipal; 2 sesiones por semana.", []],
    ["mobility", "Movilidad y flexibilidad", 1, 20, 5, 1, "10 minutos al día de estiramientos y movilidad de cadera, hombros y espalda.", ["yoga"]],
    ["yoga", "Yoga", 2, 50, 4, 2, "Clases para principiantes o programas gratuitos en vídeo; 3 veces por semana.", ["meditation", "mobility"]],
    ["calisthenics", "Calistenia (dominadas, fondos, flexiones)", 3, 80, 4, 2, "Progresiones de r/bodyweightfitness «Recommended Routine».", ["strength-training"]],
    ["martial-arts", "Artes marciales o defensa personal", 3, 150, 4, 2, "Prueba clases de judo, jiu-jitsu, boxeo o muay thai en tu ciudad y elige una.", ["discipline"]],
    ["nutrition", "Nutrición básica", 2, 20, 5, 2, "Aprende proteínas, fibra y raciones con fuentes oficiales de salud; cocina más en casa.", ["cooking-basics", "meal-prep"]],
    ["sleep", "Dormir mejor", 1, 10, 5, 2, "Lee «Why We Sleep» de Matthew Walker con espíritu crítico; horario fijo y pantalla fuera 1 h antes.", ["morning-routine"]],
    ["posture", "Mejorar la postura", 1, 10, 4, 1, "Ajusta tu puesto de trabajo y haz ejercicios de espalda 3 veces por semana.", ["mobility"]],
    ["first-aid", "Primeros auxilios y RCP", 2, 10, 5, 2, "Curso oficial de Cruz Roja o equivalente con certificado.", ["volunteering"]],
    ["hiking", "Senderismo y montaña", 2, 40, 4, 1, "Empieza con rutas cortas marcadas y aprende a leer mapas.", ["orientation", "camping"]],
    ["cycling", "Ciclismo de ruta o montaña", 2, 50, 3, 1, "Salidas de 1 h que vayan creciendo; aprende mantenimiento básico.", ["bike-repair"]],
    ["climbing", "Escalada", 3, 80, 3, 1, "Rocódromo con curso de iniciación y de seguridad.", []],
    ["dance", "Bailar (salsa, bachata, urbano…)", 2, 60, 3, 2, "Clases semanales de un estilo; practica en sociales.", ["confidence"]],
    ["quit-smoking", "Dejar de fumar", 4, 30, 5, 3, "Pide ayuda en tu centro de salud; fija fecha y elimina detonantes.", ["habit-building"]],
  ],
  mente: [
    ["meditation", "Meditación diaria", 2, 30, 5, 1, "10 minutos al día con una app gratuita o la respiración contada; registra la racha.", ["stress-management", "mindfulness"]],
    ["mindfulness", "Mindfulness (atención plena)", 2, 30, 5, 1, "Programa MBSR de 8 semanas (Jon Kabat-Zinn) o su libro «Vivir con plenitud las crisis».", ["meditation"]],
    ["stress-management", "Gestionar el estrés", 2, 20, 5, 2, "Aprende respiración, escritura expresiva y descanso planificado.", ["meditation", "journaling"]],
    ["journaling", "Diario personal", 1, 15, 4, 1, "5 minutos cada noche: qué hice, qué aprendí, qué mejoro mañana.", ["self-knowledge"]],
    ["self-knowledge", "Autoconocimiento", 2, 30, 5, 2, "Escribe tus valores, fortalezas y lo que te drena; revísalo cada mes.", ["journaling"]],
    ["emotional-intelligence", "Inteligencia emocional", 3, 40, 5, 4, "Lee «Inteligencia emocional» de Daniel Goleman y nombra tus emociones a diario.", ["communication", "empathy"]],
    ["focus-deep-work", "Trabajo profundo (deep work)", 2, 20, 5, 5, "Lee «Deep Work» de Cal Newport y haz 2 bloques diarios de 90 minutos sin móvil.", ["time-management"]],
    ["time-management", "Gestión del tiempo", 2, 15, 5, 4, "Planifica la semana el domingo y el día la noche anterior; revisa qué no hiciste y por qué.", ["focus-deep-work", "gtd"]],
    ["gtd", "Método GTD (Getting Things Done)", 2, 15, 4, 3, "Lee «Organízate con eficacia» de David Allen y vacía tu cabeza en una lista.", ["time-management"]],
    ["memory", "Técnicas de memoria", 2, 20, 4, 3, "Aprende el palacio de la memoria y la repetición espaciada con Anki.", ["spaced-repetition"]],
    ["spaced-repetition", "Estudiar con repetición espaciada (Anki)", 1, 10, 5, 3, "Instala Anki y crea tarjetas de lo que estudias; 15 minutos al día.", ["memory", "lenguas-general"]],
    ["speed-learning", "Aprender a aprender", 2, 20, 5, 4, "Curso gratuito «Learning How to Learn» de Barbara Oakley (Coursera).", ["spaced-repetition"]],
    ["critical-thinking", "Pensamiento crítico", 3, 40, 5, 4, "Lee «Pensar rápido, pensar despacio» de Daniel Kahneman y aprende los sesgos más comunes.", ["logic", "debate"]],
    ["logic", "Lógica formal", 3, 40, 4, 3, "Curso de lógica introductoria (por ejemplo, «Introduction to Logic» de Stanford en Coursera).", ["critical-thinking", "philosophy-intro"]],
    ["habit-building", "Construir hábitos", 1, 10, 5, 3, "Lee «Hábitos atómicos» de James Clear y empieza con un hábito de 2 minutos.", ["discipline"]],
    ["discipline", "Autodisciplina", 3, 30, 5, 4, "Haz cada día una cosa difícil a la misma hora, sin negociar contigo mismo.", ["habit-building"]],
    ["digital-detox", "Desintoxicación digital", 2, 10, 5, 2, "Lee «Minimalismo digital» de Cal Newport y haz 30 días sin redes no esenciales.", ["focus-deep-work"]],
    ["chess", "Ajedrez", 3, 150, 3, 2, "Lecciones gratuitas de Lichess y 10 problemas tácticos al día.", ["critical-thinking"]],
    ["creativity", "Creatividad", 2, 20, 4, 3, "Lee «Roba como un artista» de Austin Kleon y genera 10 ideas al día durante un mes.", ["writing"]],
  ],
  filosofia: [
    ["philosophy-intro", "Introducción a la filosofía", 2, 30, 4, 1, "Lee «El mundo de Sofía» de Jostein Gaarder o el curso «Introduction to Philosophy» (Universidad de Edimburgo).", ["logic", "ethics"]],
    ["stoicism", "Estoicismo práctico", 2, 25, 5, 2, "Lee a Epicteto, Séneca y Marco Aurelio; practica la revisión nocturna estoica.", ["meditations-aurelius", "letters-seneca"]],
    ["ethics", "Ética", 3, 40, 4, 1, "Lee «Ética a Nicómaco» de Aristóteles con una guía y discute casos reales.", ["philosophy-intro"]],
    ["eastern-philosophy", "Filosofía oriental (Confucio, Laozi, budismo)", 3, 40, 4, 1, "Lee las «Analectas» de Confucio y el «Tao Te Ching» en buenas traducciones comentadas.", ["tao-te-ching", "analects"]],
    ["existentialism", "Existencialismo", 3, 40, 3, 1, "Lee «El existencialismo es un humanismo» de Sartre y «El mito de Sísifo» de Camus.", ["philosophy-intro"]],
    ["political-philosophy", "Filosofía política", 4, 60, 4, 1, "Lee «La República» de Platón y «Sobre la libertad» de John Stuart Mill.", ["republic-plato"]],
    ["philosophy-of-science", "Filosofía de la ciencia", 4, 40, 3, 1, "Lee «La estructura de las revoluciones científicas» de Thomas Kuhn.", ["critical-thinking"]],
  ],
  lectura: [
    ["meditations-aurelius", "Leer «Meditaciones» de Marco Aurelio", 2, 6, 5, 1, "Una o dos notas cada mañana y subraya lo que quieras aplicar ese día.", ["stoicism"]],
    ["letters-seneca", "Leer «Cartas a Lucilio» de Séneca", 3, 15, 5, 1, "Una carta al día con una frase copiada en tu diario.", ["stoicism"]],
    ["enchiridion", "Leer el «Enquiridión» de Epicteto", 1, 2, 5, 1, "Léelo de una vez y luego relee un capítulo al día.", ["stoicism"]],
    ["tao-te-ching", "Leer el «Tao Te Ching» de Laozi", 2, 4, 4, 1, "Un capítulo por día comparando dos traducciones.", ["eastern-philosophy"]],
    ["analects", "Leer las «Analectas» de Confucio", 3, 10, 4, 1, "Edición comentada; un libro (capítulo) por semana.", ["eastern-philosophy"]],
    ["art-of-war", "Leer «El arte de la guerra» de Sun Tzu", 2, 3, 4, 3, "Léelo pensando en estrategia personal y profesional; resume cada capítulo en una línea.", ["strategy"]],
    ["republic-plato", "Leer «La República» de Platón", 4, 18, 4, 1, "Un libro (de los diez) por semana con una guía de lectura.", ["political-philosophy"]],
    ["apology-plato", "Leer «Apología de Sócrates» de Platón", 2, 2, 4, 1, "Léelo en una tarde y escribe qué defenderías tú hasta el final.", ["philosophy-intro"]],
    ["nicomachean", "Leer «Ética a Nicómaco» de Aristóteles", 4, 15, 4, 1, "Con edición anotada; un libro por semana.", ["ethics"]],
    ["mans-search", "Leer «El hombre en busca de sentido» de Viktor Frankl", 2, 5, 5, 1, "Léelo en una semana y escribe tu propio «para qué».", ["self-knowledge"]],
    ["beyond-good-evil", "Leer «Más allá del bien y del mal» de Nietzsche", 4, 10, 3, 1, "Un aforismo cada vez, con una guía introductoria.", ["existentialism"]],
    ["zarathustra", "Leer «Así habló Zaratustra» de Nietzsche", 4, 12, 3, 1, "Con una introducción previa; una parte por semana.", ["existentialism"]],
    ["myth-sisyphus", "Leer «El mito de Sísifo» de Albert Camus", 3, 5, 3, 1, "Léelo despacio, ensayo a ensayo.", ["existentialism"]],
    ["walden", "Leer «Walden» de Henry David Thoreau", 3, 10, 3, 1, "Un capítulo por semana y un día de vida sencilla como experimento.", ["minimalism"]],
    ["sapiens", "Leer «Sapiens» de Yuval Noah Harari", 2, 14, 4, 1, "Una parte por semana y discútela con alguien.", ["history-world"]],
    ["thinking-fast-slow", "Leer «Pensar rápido, pensar despacio» de Daniel Kahneman", 3, 15, 5, 3, "Un capítulo cada dos días con un ejemplo propio de cada sesgo.", ["critical-thinking"]],
    ["atomic-habits", "Leer «Hábitos atómicos» de James Clear", 1, 6, 5, 3, "Aplica una técnica de cada capítulo antes de pasar al siguiente.", ["habit-building"]],
    ["deep-work-book", "Leer «Deep Work» de Cal Newport", 2, 7, 5, 4, "Al terminar, planifica tus bloques de trabajo profundo de la semana.", ["focus-deep-work"]],
    ["how-to-win-friends", "Leer «Cómo ganar amigos e influir sobre las personas» de Dale Carnegie", 1, 7, 5, 4, "Practica un principio por semana en conversaciones reales.", ["communication", "social-skills"]],
    ["seven-habits", "Leer «Los 7 hábitos de la gente altamente efectiva» de Stephen Covey", 2, 12, 5, 4, "Un hábito por semana con su ejercicio práctico.", ["time-management"]],
    ["rich-dad", "Leer «Padre rico, padre pobre» de Robert Kiyosaki", 1, 6, 4, 3, "Léelo como motivación y contrasta sus ideas con fuentes de finanzas serias.", ["finance-literacy"]],
    ["don-quixote", "Leer «Don Quijote de la Mancha» de Cervantes", 4, 40, 3, 1, "Un capítulo al día; una edición anotada ayuda mucho.", ["literature"]],
    ["one-hundred-years", "Leer «Cien años de soledad» de Gabriel García Márquez", 3, 14, 3, 1, "Haz un árbol genealógico de los Buendía mientras lees.", ["literature"]],
    ["crime-punishment", "Leer «Crimen y castigo» de Dostoievski", 4, 20, 3, 1, "Una parte por semana; anota la evolución de Raskólnikov.", ["literature", "russian-literature"]],
    ["brothers-karamazov", "Leer «Los hermanos Karamázov» de Dostoievski", 5, 35, 3, 1, "Un libro por semana; lee «El gran inquisidor» dos veces.", ["russian-literature"]],
    ["war-and-peace", "Leer «Guerra y paz» de Tolstói", 5, 50, 3, 1, "Un capítulo al día durante un año, como propone mucha gente.", ["russian-literature"]],
    ["1984", "Leer «1984» de George Orwell", 2, 10, 4, 1, "Léelo y compáralo con el mundo actual en una página.", ["literature"]],
    ["brave-new-world", "Leer «Un mundo feliz» de Aldous Huxley", 2, 8, 4, 1, "Léelo después de «1984» y compara ambas distopías.", ["literature"]],
    ["little-prince", "Leer «El principito» de Antoine de Saint-Exupéry", 1, 2, 3, 1, "Léelo en voz alta; anota la frase que más te toque.", ["literature"]],
    ["divine-comedy", "Leer «La divina comedia» de Dante", 5, 30, 3, 1, "Un canto al día con notas; empieza por el Infierno.", ["literature", "italian-culture"]],
    ["odyssey", "Leer «La Odisea» de Homero", 3, 15, 3, 1, "Un canto cada dos días con un mapa del viaje de Ulises.", ["literature", "history-ancient"]],
    ["hamlet", "Leer «Hamlet» de Shakespeare", 3, 6, 3, 1, "Lee un acto por día y mira después una buena adaptación.", ["literature", "theatre"]],
    ["poetry-reading", "Leer poesía (Neruda, Machado, Lorca…)", 2, 20, 3, 1, "Un poema al día en voz alta; aprende uno de memoria al mes.", ["literature", "poetry-writing"]],
    ["literature", "Literatura universal", 3, 200, 3, 1, "Haz una lista de 20 clásicos y lee uno al mes alternando con libros actuales.", ["writing"]],
    ["russian-literature", "Literatura rusa", 4, 120, 3, 1, "Empieza por cuentos de Chéjov y luego Dostoievski y Tolstói.", ["literature", "lang-russian-a1"]],
    ["speed-reading", "Leer más y mejor (lectura activa)", 2, 15, 5, 3, "Lee «Cómo leer un libro» de Mortimer Adler y aplica la lectura analítica.", ["literature"]],
    ["reading-habit", "Hábito de leer 20 páginas al día", 1, 30, 5, 2, "Deja el libro en la almohada y lee antes de dormir; registra páginas.", ["literature"]],
  ],
  espiritual: [
    ["spiritual-practice", "Práctica espiritual diaria", 1, 30, 5, 1, "10 minutos diarios de oración, meditación o silencio según tu tradición.", ["meditation", "gratitude"]],
    ["gratitude", "Gratitud diaria", 1, 5, 5, 1, "Escribe tres cosas concretas por las que estás agradecido cada noche.", ["journaling"]],
    ["sacred-texts", "Leer textos sagrados de varias tradiciones", 3, 60, 4, 1, "Lee la Biblia, el Bhagavad Gita, el Dhammapada o el Corán en ediciones comentadas, con respeto y curiosidad.", ["comparative-religion"]],
    ["comparative-religion", "Religiones comparadas", 3, 40, 4, 1, "Lee «Las religiones del mundo» de Huston Smith.", ["sacred-texts", "history-world"]],
    ["retreat", "Hacer un retiro de silencio", 3, 30, 4, 1, "Busca un retiro de fin de semana; prepárate con meditación diaria antes.", ["meditation"]],
    ["purpose", "Definir tu propósito y valores", 2, 10, 5, 2, "Escribe tu elogio fúnebre ideal y deduce de él tus 5 valores.", ["self-knowledge"]],
    ["forgiveness", "Practicar el perdón", 3, 15, 5, 1, "Escribe una carta (sin enviarla) a alguien que te hirió; trabaja con apoyo si lo necesitas.", ["emotional-intelligence"]],
    ["dhammapada", "Leer el «Dhammapada»", 2, 4, 4, 1, "Un capítulo al día con una meditación breve.", ["sacred-texts", "eastern-philosophy"]],
    ["bhagavad-gita", "Leer el «Bhagavad Gita»", 3, 6, 4, 1, "Edición con comentarios; un capítulo cada dos días.", ["sacred-texts"]],
  ],
  cultura: [
    ["history-world", "Historia universal", 3, 80, 4, 1, "La serie de vídeos «Crash Course World History» o un buen manual; haz una línea del tiempo.", ["history-ancient", "geography"]],
    ["history-ancient", "Historia antigua (Grecia y Roma)", 3, 40, 3, 1, "Lee «SPQR» de Mary Beard.", ["history-world"]],
    ["history-china", "Historia de China", 3, 40, 4, 1, "Lee una historia general de China y relaciónala con lo que estudies del idioma.", ["lang-chinese-a1", "eastern-philosophy"]],
    ["history-latam", "Historia de América Latina", 3, 40, 3, 1, "Lee «Las venas abiertas de América Latina» de Eduardo Galeano contrastándolo con otras fuentes.", ["history-world"]],
    ["art-history", "Historia del arte", 3, 60, 3, 2, "Lee «La historia del arte» de Ernst Gombrich, un capítulo por semana.", ["museums"]],
    ["museums", "Visitar un museo al mes", 1, 24, 3, 1, "Elige uno al mes y prepara 3 obras antes de ir.", ["art-history"]],
    ["cinema", "Cine clásico (100 películas esenciales)", 1, 200, 2, 1, "Una película clásica por semana con una nota breve después.", ["storytelling"]],
    ["theatre", "Teatro e interpretación", 3, 80, 3, 2, "Apúntate a un grupo de teatro amateur.", ["public-speaking", "confidence"]],
    ["drawing", "Dibujo", 3, 100, 3, 2, "Lee «Aprender a dibujar con el lado derecho del cerebro» de Betty Edwards; 20 minutos al día.", ["illustration", "painting"]],
    ["painting", "Pintura (acuarela u óleo)", 3, 100, 2, 2, "Clases o vídeos de acuarela; una pequeña pintura por semana.", ["drawing"]],
    ["calligraphy", "Caligrafía", 2, 40, 2, 2, "Caligrafía latina o china con un cuaderno de práctica diario.", ["lang-chinese-a1"]],
    ["writing", "Escribir bien", 3, 80, 5, 5, "Lee «Mientras escribo» de Stephen King y escribe 500 palabras al día.", ["copywriting", "storytelling", "blogging"]],
    ["storytelling", "Contar historias (storytelling)", 2, 30, 5, 4, "Lee «Story» de Robert McKee o «Storyworthy» de Matthew Dicks y cuenta una anécdota preparada cada semana.", ["public-speaking", "content-creation"]],
    ["poetry-writing", "Escribir poesía", 2, 40, 2, 1, "Un poema breve al día durante 30 días; lee poesía cada semana.", ["poetry-reading"]],
    ["blogging", "Escribir un blog", 2, 60, 4, 3, "Publica un artículo por semana sobre lo que aprendes.", ["writing", "seo"]],
    ["novel", "Escribir una novela corta", 4, 200, 2, 2, "Reto NaNoWriMo: 50 000 palabras en un mes, luego corrige.", ["writing"]],
    ["geography", "Geografía del mundo", 2, 20, 3, 1, "Aprende países, capitales y mapas con Seterra y Anki.", ["travel"]],
    ["travel", "Viajar barato y con propósito", 2, 30, 4, 2, "Planifica un viaje con presupuesto cerrado y un objetivo (idioma, cultura, naturaleza).", ["lenguas-general"]],
    ["italian-culture", "Cultura italiana (arte, cine y cocina)", 2, 30, 2, 1, "Combina cine de Fellini, arte renacentista y recetas regionales.", ["lang-italian-a1"]],
    ["minimalism", "Vida minimalista", 2, 15, 4, 3, "Reto de 30 días sacando de casa un objeto más cada día.", ["home-organization"]],
    ["mythology", "Mitología comparada", 2, 30, 2, 1, "Lee «El héroe de las mil caras» de Joseph Campbell.", ["storytelling"]],
  ],
  musica: [
    ["guitar", "Tocar la guitarra", 3, 150, 3, 2, "Aprende 4 acordes básicos y canciones sencillas; 20 minutos diarios con metrónomo.", ["music-theory"]],
    ["piano", "Tocar el piano", 3, 200, 3, 2, "Método para adultos o apps de piano; 20 minutos diarios.", ["music-theory"]],
    ["singing", "Cantar con técnica", 3, 100, 3, 2, "Clases de técnica vocal; ejercicios de respiración a diario.", ["public-speaking"]],
    ["music-theory", "Teoría musical", 3, 60, 3, 2, "Lecciones gratuitas de musictheory.net.", ["piano", "guitar", "music-production"]],
    ["music-production", "Producción musical", 4, 150, 3, 3, "Aprende con un programa gratuito y termina una canción al mes.", ["music-theory"]],
    ["dj", "Mezclar como DJ", 3, 60, 2, 3, "Controladora básica y práctica de beatmatching.", ["music-production"]],
    ["ukulele", "Tocar el ukelele", 2, 40, 2, 1, "4 acordes y tus primeras 5 canciones en un mes.", ["music-theory"]],
    ["drums", "Tocar la batería", 3, 150, 2, 2, "Clases y práctica con pad y metrónomo.", ["music-theory"]],
    ["ear-training", "Educación auditiva", 3, 40, 3, 1, "Ejercicios de intervalos y acordes 10 minutos al día.", ["music-theory"]],
  ],
};
